SELECT ATENDIME.CD_ATENDIMENTO "A",
       PACIENTE.CD_PACIENTE "B",
       PACIENTE.DT_NASCIMENTO "C",
       PACIENTE.TP_SEXO "D",
       PACIENTE.NR_CEP "E",
       PACIENTE.NM_BAIRRO AS "F",
       CIDADE.NM_CIDADE "G",
       CIDADE.CD_UF "H",
       CONVENIO.NR_REGISTRO_OPERADORA_ANS "I",NULL "J",
       ATENDIME.DT_ATENDIMENTO "K",
       ATENDIME.DT_ALTA "L",
       ATENDIME.CD_CID "M",
       ATENDIME.CD_CID "N",
       ATENDIME.CD_CID "O",
       CASE WHEN ATENDIME.CD_PRO_INT IS NULL THEN ATENDIME.CD_PRO_INT_PROCEDIMENTO_ENTRAD
            ELSE ATENDIME.CD_PRO_INT END "P",
       CASE WHEN ATENDIME.CD_ATENDIMENTO = AVISO_CIRURGIA.CD_ATENDIMENTO THEN MIN(TO_CHAR(AVISO_CIRURGIA.DT_REALIZACAO,'DD/MM/YYYY'))
       ELSE NULL END "Q",
       CASE WHEN ATENDIME.CD_PRO_INT IS NULL THEN ATENDIME.CD_PRO_INT_PROCEDIMENTO_ENTRAD
            ELSE ATENDIME.CD_PRO_INT END "R",
       CASE WHEN ATENDIME.CD_ATENDIMENTO = AVISO_CIRURGIA.CD_ATENDIMENTO THEN MAX(TO_CHAR(AVISO_CIRURGIA.DT_REALIZACAO,'DD/MM/YYYY'))
       ELSE NULL END "S",
       MOT_ALT.DS_MOT_ALT "T",
       Min(UTI.DT_MOV) "U",
       max(UTI.DT_MOV) "V",
       quant.qtd "W",
       Max(MED.MET) "X",
       MED.QTD "Y",
       NULL "Z",
       ORI_ATE.DS_ORI_ATE "AA"
  FROM AVISO_CIRURGIA,
       ATENDIME,
       PACIENTE,
       CONVENIO,
       PRE_MED,
       CIDADE,
       ORI_ATE,
       MOV_INT,
       MOT_ALT,
       (SELECT MOV_INT.CD_MOV_INT, MIN(MOV_INT.DT_MOV_INT) DT_MOV
         FROM MOV_INT
        WHERE MOV_INT.CD_LEITO IN (154,155,156,157,158,159,160,161,162,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328)
        GROUP BY MOV_INT.CD_MOV_INT) UTI,
       (SELECT cd_atendimento, Count(MOV_INT.CD_MOV_INT) qtd
          FROM MOV_INT
         WHERE MOV_INT.CD_LEITO IN (154,155,156,157,158,159,160,161,162,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328)
         GROUP BY cd_atendimento)quant,
       (SELECT 'S' MET,PRE_MED.CD_PRE_MED
          FROM PRE_MED,ITPRE_MED
         WHERE ITPRE_MED.CD_PRE_MED = PRE_MED.CD_PRE_MED(+)
           AND ITPRE_MED.CD_TIP_PRESC = 2429
          GROUP BY PRE_MED.CD_PRE_MED) MED,
       (SELECT PRE_MED.CD_ATENDIMENTO,Max(To_Date(PRE_MED.DT_PRE_MED)) - Min(To_Date(PRE_MED.DT_PRE_MED)) QTD
          FROM PRE_MED,ITPRE_MED
         WHERE ITPRE_MED.CD_PRE_MED = PRE_MED.CD_PRE_MED(+)
           AND ITPRE_MED.CD_TIP_PRESC = 2429
          GROUP BY PRE_MED.CD_ATENDIMENTO) MED
 WHERE PRE_MED.CD_ATENDIMENTO(+) = ATENDIME.CD_ATENDIMENTO
   AND AVISO_CIRURGIA.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO(+)
   AND MOV_INT.CD_ATENDIMENTO(+) = ATENDIME.CD_ATENDIMENTO
   AND MOV_INT.CD_ATENDIMENTO = PRE_MED.CD_ATENDIMENTO
   AND MOV_INT.CD_MOV_INT = UTI.CD_MOV_INT(+)
   AND mov_int.cd_atendimento = quant.cd_atendimento(+)
   AND ATENDIME.CD_ATENDIMENTO = MED.CD_ATENDIMENTO(+)
   AND PRE_MED.CD_PRE_MED = MED.CD_PRE_MED(+)
   AND PACIENTE.CD_CIDADE = CIDADE.CD_CIDADE(+)
   AND ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE(+)
   AND ATENDIME.CD_ORI_ATE = ORI_ATE.CD_ORI_ATE(+)
   AND ATENDIME.CD_CONVENIO = CONVENIO.CD_CONVENIO(+)
   AND ATENDIME.CD_MOT_ALT = MOT_ALT.CD_MOT_ALT(+)
   AND TRUNC(ATENDIME.DT_ALTA)BETWEEN '01/01/2019' AND '31/12/2019'
   AND ATENDIME.TP_ATENDIMENTO = 'I'
GROUP BY CASE WHEN ATENDIME.CD_PRO_INT IS NULL THEN ATENDIME.CD_PRO_INT_PROCEDIMENTO_ENTRAD
         ELSE ATENDIME.CD_PRO_INT END,
         AVISO_CIRURGIA.CD_ATENDIMENTO,
         ATENDIME.CD_ATENDIMENTO,
         PACIENTE.CD_PACIENTE,
         PACIENTE.DT_NASCIMENTO,
         PACIENTE.TP_SEXO,
         PACIENTE.NR_CEP,
         PACIENTE.NM_BAIRRO,
         CIDADE.NM_CIDADE,
         CIDADE.CD_UF,
         CONVENIO.NR_REGISTRO_OPERADORA_ANS,
         ATENDIME.DT_ATENDIMENTO,
         ATENDIME.DT_ALTA,
         ATENDIME.CD_CID,
         ORI_ATE.DS_ORI_ATE,
         MOT_ALT.DS_MOT_ALT,
         quant.qtd,
         MED.QTD
ORDER BY 1 ASC
