SELECT ATENDIME.CD_ATENDIMENTO,
       PACIENTE.CD_PACIENTE,
       PACIENTE.NM_PACIENTE,
       To_Char(ATENDIME.DT_ATENDIMENTO,'DD/MM/YYYY')DT_ATENDIMENTO,
       CONVENIO.NM_CONVENIO,
       ATENDIME.CD_ORI_ATE,
       PRESTADOR.NM_PRESTADOR,
       EXA_RX.DS_EXA_RX
  FROM DBAMV.PRESTADOR,
       DBAMV.ATENDIME,
       DBAMV.CONVENIO,
       DBAMV.PACIENTE,
       DBAMV.ITPRE_MED,
       DBAMV.PRE_MED,
       DBAMV.TIP_PRESC,
       DBAMV.EXA_RX
 WHERE ATENDIME.CD_PACIENTE  = PACIENTE.CD_PACIENTE
   AND ATENDIME.CD_PRESTADOR = PRESTADOR.CD_PRESTADOR
   AND ATENDIME.CD_CONVENIO = CONVENIO.CD_CONVENIO
   AND PRE_MED.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO
   AND ITPRE_MED.CD_PRE_MED = PRE_MED.CD_PRE_MED
   AND ITPRE_MED.CD_TIP_PRESC = TIP_PRESC.CD_TIP_PRESC
   AND TIP_PRESC.CD_EXA_RX = EXA_RX.CD_EXA_RX
   AND ATENDIME.TP_ATENDIMENTO = 'A'
   AND ATENDIME.CD_ORI_ATE = '32'
   AND CONVENIO.CD_CONVENIO NOT IN 2
   AND ATENDIME.CD_ESPECIALID NOT IN (6)
   AND ATENDIME.DT_ATENDIMENTO BETWEEN '01/01/2019' AND '02/06/2020'
   --AND PACIENTE.CD_PACIENTE = 39541

GROUP BY ATENDIME.CD_ATENDIMENTO,
         PACIENTE.CD_PACIENTE,
         To_Char(ATENDIME.DT_ATENDIMENTO,'DD/MM/YYYY'),
         CONVENIO.NM_CONVENIO,
         PRESTADOR.NM_PRESTADOR,
         PACIENTE.NM_PACIENTE,
         ATENDIME.CD_ORI_ATE,
         EXA_RX.DS_EXA_RX

ORDER BY 1 DESC
