SELECT PED_RX.CD_PED_RX,
       ATENDIME.CD_ATENDIMENTO,
       PACIENTE.CD_PACIENTE,
       PACIENTE.NM_PACIENTE,
       To_Char(PED_RX.DT_PEDIDO,'DD/MM/YYYY') DT_PEDIDO,
       CONVENIO.NM_CONVENIO,
       PED_RX.NM_PRESTADOR,
       EXA_RX.DS_EXA_RX
  FROM DBAMV.PED_RX,
       DBAMV.ATENDIME,
       DBAMV.PACIENTE,
       DBAMV.CONVENIO,
       DBAMV.ITPED_RX,
       DBAMV.EXA_RX
 WHERE PED_RX.CD_ATENDIMENTO = ATENDIME.CD_ATENDIMENTO
   AND ATENDIME.CD_CONVENIO = CONVENIO.CD_CONVENIO
   AND ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
   AND ITPED_RX.CD_PED_RX = PED_RX.CD_PED_RX
   AND ITPED_RX.CD_EXA_RX = EXA_RX.CD_EXA_RX
   AND ATENDIME.CD_LOC_PROCED IN (13,16)
   AND ATENDIME.CD_ORI_ATE IN (4)
   AND CONVENIO.CD_CONVENIO NOT IN (2)
   AND PED_RX.CD_PRESTADOR IS NOT NULL
   AND PED_RX.DT_PEDIDO BETWEEN '01/01/2020' AND '02/06/2020'
ORDER BY CD_PED_RX DESC
